[wokwi]
version = 1
elf = 'test/dfplayer/build/arduino.avr.uno/dfplayer.ino.elf'
firmware = 'test/dfplayer/build/arduino.avr.uno/dfplayer.ino.hex'

[[chip]]
name = 'dfplayer-mini'
binary = 'dist/chip.wasm'
